"""
mempalace schema — Post-migration schema validation and patching.

Compares a migrated ChromaDB palace's SQLite schema against a reference
schema generated by the currently installed ChromaDB version, then patches
any structural gaps (missing tables, columns, indexes).

Also fixes a known data-level issue where seq_id values are stored as
BLOBs instead of INTEGERs after cross-version migration.
"""

import os
import shutil
import sqlite3
import tempfile

# FTS5 auxiliary tables are auto-managed by SQLite — skip them.
_FTS_SUFFIXES = ("_content", "_docsize", "_data", "_idx", "_config")

# Internal SQLite tables to ignore.
_INTERNAL_TABLES = frozenset({"sqlite_sequence", "sqlite_stat1", "sqlite_stat4"})


def snapshot_schema(db_path: str) -> dict:
    """Capture tables, columns, and indexes from a ChromaDB SQLite database.

    Returns::

        {
            "tables": {
                "table_name": {
                    "columns": [{"name": str, "type": str, "notnull": bool, "pk": bool}, ...],
                    "create_sql": str,  # from sqlite_master
                },
                ...
            },
            "indexes": {
                "index_name": {
                    "table": str,
                    "create_sql": str,
                },
                ...
            },
        }
    """
    conn = sqlite3.connect(db_path)
    try:
        schema: dict = {"tables": {}, "indexes": {}}

        # Enumerate tables
        tables = conn.execute(
            "SELECT name, sql FROM sqlite_master WHERE type = 'table' ORDER BY name"
        ).fetchall()

        for tname, create_sql in tables:
            if tname.startswith("sqlite_") or tname in _INTERNAL_TABLES:
                continue
            # Skip FTS5 auxiliary tables
            if any(tname.endswith(sfx) for sfx in _FTS_SUFFIXES):
                continue

            columns = []
            for row in conn.execute(f"PRAGMA table_info('{tname}')").fetchall():
                # row: (cid, name, type, notnull, default, pk)
                columns.append(
                    {
                        "name": row[1],
                        "type": row[2],
                        "notnull": bool(row[3]),
                        "pk": bool(row[5]),
                    }
                )

            schema["tables"][tname] = {
                "columns": columns,
                "create_sql": create_sql or "",
            }

        # Enumerate indexes (skip auto-indexes)
        indexes = conn.execute(
            "SELECT name, tbl_name, sql FROM sqlite_master "
            "WHERE type = 'index' AND sql IS NOT NULL ORDER BY name"
        ).fetchall()

        for iname, tbl_name, create_sql in indexes:
            # Skip indexes on FTS auxiliary tables
            if any(tbl_name.endswith(sfx) for sfx in _FTS_SUFFIXES):
                continue
            schema["indexes"][iname] = {
                "table": tbl_name,
                "create_sql": create_sql,
            }

        return schema
    finally:
        conn.close()


def create_reference_schema() -> dict:
    """Create a throwaway ChromaDB palace and snapshot its schema.

    Adds one dummy document to force ChromaDB to materialize the full
    schema (some tables/indexes are only created on first write).

    Returns the snapshot dict from ``snapshot_schema``.
    """
    import chromadb

    tmp_dir = tempfile.mkdtemp(prefix="mempalace_ref_schema_")
    try:
        client = chromadb.PersistentClient(path=tmp_dir)
        col = client.get_or_create_collection("mempalace_drawers")
        # Provide dummy embeddings to bypass the ONNX embedding model entirely.
        # We only need the schema structure, not meaningful embeddings.
        col.add(
            ids=["__schema_probe__"],
            documents=["schema probe document"],
            metadatas=[{"wing": "test", "room": "test"}],
            embeddings=[[0.0] * 384],
        )
        del col
        del client

        ref_db = os.path.join(tmp_dir, "chroma.sqlite3")
        return snapshot_schema(ref_db)
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)


def compare_schemas(reference: dict, actual: dict) -> list[dict]:
    """Compare a reference schema against an actual schema.

    Returns a list of gap dicts::

        {
            "kind": "missing_table" | "missing_column" | "missing_index",
            "table": str,
            "detail": str,
            "fix_sql": str,
        }
    """
    gaps = []

    # Missing tables
    for tname, tinfo in reference["tables"].items():
        if tname not in actual["tables"]:
            gaps.append(
                {
                    "kind": "missing_table",
                    "table": tname,
                    "detail": f"Table '{tname}' missing from migrated database",
                    "fix_sql": tinfo["create_sql"],
                }
            )
            continue

        # Missing columns
        ref_cols = {c["name"] for c in tinfo["columns"]}
        act_cols = {c["name"] for c in actual["tables"][tname]["columns"]}
        for col_name in ref_cols - act_cols:
            ref_col = next(c for c in tinfo["columns"] if c["name"] == col_name)
            col_type = ref_col["type"] or "TEXT"
            not_null = " NOT NULL DEFAULT ''" if ref_col["notnull"] else ""
            gaps.append(
                {
                    "kind": "missing_column",
                    "table": tname,
                    "detail": f"Column '{col_name}' missing from table '{tname}'",
                    "fix_sql": f"ALTER TABLE {tname} ADD COLUMN {col_name} {col_type}{not_null}",
                }
            )

    # Missing indexes
    for iname, iinfo in reference["indexes"].items():
        if iname not in actual["indexes"]:
            gaps.append(
                {
                    "kind": "missing_index",
                    "table": iinfo["table"],
                    "detail": f"Index '{iname}' missing from table '{iinfo['table']}'",
                    "fix_sql": iinfo["create_sql"],
                }
            )

    return gaps


def fix_blob_seq_ids(db_path: str) -> int:
    """Convert BLOB seq_id values to INTEGER in embeddings and max_seq_id.

    ChromaDB 0.6.x -> 1.x migrations sometimes produce BLOB-encoded
    seq_ids that cause runtime failures. This converts them in-place.

    Returns the total number of rows fixed.
    """
    fixed = 0
    conn = sqlite3.connect(db_path)
    try:
        for table in ("embeddings", "max_seq_id"):
            try:
                rows = conn.execute(
                    f"SELECT rowid, seq_id FROM {table} WHERE typeof(seq_id) = 'blob'"
                ).fetchall()
            except sqlite3.OperationalError:
                # Table doesn't exist — that's fine
                continue
            if not rows:
                continue
            updates = []
            for rowid, blob in rows:
                if isinstance(blob, bytes) and len(blob) > 0:
                    updates.append((int.from_bytes(blob, byteorder="big"), rowid))
            if updates:
                conn.executemany(f"UPDATE {table} SET seq_id = ? WHERE rowid = ?", updates)
                fixed += len(updates)
        conn.commit()
    finally:
        conn.close()
    return fixed


def validate_and_patch(db_path: str, reference: dict | None = None) -> tuple[bool, list[str]]:
    """Validate a migrated palace's schema and patch gaps.

    Args:
        db_path: Path to the migrated ``chroma.sqlite3``.
        reference: Reference schema dict. Created automatically if not provided.

    Returns:
        ``(success, actions_taken)`` where *success* is True if all patches
        applied cleanly and *actions_taken* lists human-readable descriptions.
    """
    actions: list[str] = []

    if reference is None:
        reference = create_reference_schema()

    actual = snapshot_schema(db_path)
    gaps = compare_schemas(reference, actual)

    if gaps:
        conn = sqlite3.connect(db_path)
        try:
            for gap in gaps:
                try:
                    conn.execute(gap["fix_sql"])
                    actions.append(f"Fixed {gap['kind']}: {gap['detail']}")
                except sqlite3.OperationalError as exc:
                    actions.append(f"FAILED {gap['kind']}: {gap['detail']} ({exc})")
                    return False, actions
            conn.commit()
        finally:
            conn.close()
    else:
        actions.append("Schema OK — no structural gaps detected")

    # Fix BLOB seq_ids (data-level issue, not detectable by DDL comparison)
    blob_fixed = fix_blob_seq_ids(db_path)
    if blob_fixed:
        actions.append(f"Fixed {blob_fixed} BLOB seq_id values -> INTEGER")

    return True, actions
